services:
  forum:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: projet-forum

    ports:
      - "8080:8080"

    volumes:
      - ./back-end/database/_sql:/app/back-end/database/_sql
      - forum-uploads:/app/front-end/static/uploads

    restart: unless-stopped

volumes:
  forum-uploads:
